 CREATE TABLE user_info2 (
  UI_NUM INT AUTO_INCREMENT PRIMARY KEY,
  UI_NAME VARCHAR(100) NOT NULL,
  UI_ID VARCHAR(30) NOT NULL,
  UI_PWD VARCHAR(30) NOT NULL
);

SELECT * FROM user_info2;


SELECT * FROM user_info2 WHERE UI_ID='HONG';

SELECT * FROM user_info2 WHERE UI_NAME='김%' && UI_ID='KIM'

DELETE FROM user_info2 WHERE UI_NUM=3

SELECT * FROM user_info2 WHERE UI_ID='KIM' AND LIKE UI_NAME='김%'