CREATE TABLE MENU_INFO(
MI_NUM INT AUTO_INCREMENT PRIMARY KEY,
MI_NAME VARCHAR(30) NOT NULL,
MI_PRICE INT DEFAULT 0
);
SELECT * FROM MENU_INFO;

INSERT INTO menu_info(	)
VALUES ('김밥', 3000, '기본야채김밥');

UPDATE MENU_INFO SET MI_NAME='야채김밥', MI_PRICE=4000, MI_DESC='JMT' WHERE MI_NUM =1;

DELETE FROM MENU_INFO WHERE MI_NUM = 1;

ALTER TABLE MENU_INFO add COLUMN MI_PATH VARCHAR(400);

DESC menu_info;

-- 글넘버, 글제목, 본문, 작성자, 작성일자.
CREATE TABLE BOARD_INFO (
	BI_NUM INT AUTO_INCREMENT PRIMARY KEY,
	BI_TITLE VARCHAR(50) NOT NULL,
	BI_BODY VARCHAR(4000) NOT NULL,
	BI_AUTHOR VARCHAR(50) NOT NULL,
	CREDAT DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO BOARD_INFO (BI_TITLE, BI_BODY, BI_AUTHOR )VALUES('제목입니다.','본문내용은 VARCHAR (4000)', 'SKY');
INSERT INTO BOARD_INFO (BI_TITLE, BI_BODY, BI_AUTHOR )VALUES('제목입니다.','본문내용은 VARCHAR (4000)', 'SKY');
INSERT INTO BOARD_INFO (BI_TITLE, BI_BODY, BI_AUTHOR )VALUES('제목입니다.','본문내용은 VARCHAR (4000)', 'SKY');

UPDATE BOARD_INFO SET BI_TITLE='바뀐제목', BI_BODY='바뀐본문내용' WHERE BI_NUM=1;

DROP TABLE BOARD_INFO;

SELECT BI_NUM, BI_TITLE, BI_BODY, BI_AUTHOR, CREDAT FROM BOARD_INFO;

DELETE FROM BOARD_INFO WHERE BI_NUM =4;


SELECT * FROM user_info2;
ALTER TABLE user_info2 ADD UI_EMAIL VARCHAR(255) NOT NULL

